version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - yasuyuky
  ignore:
  - dependency-name: hyper
    versions:
    - 0.14.3
    - 0.14.7
- package-ecosystem: docker
  directory: "/test/client"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - yasuyuky
- package-ecosystem: docker
  directory: "/test/json-server"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - yasuyuky
